language: ruby
rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - 2.3.8

before_install: gem install bundler -v 1.11.2
install: bundle install --without doc --retry=3
script:
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter

env:
  global:
    - 'WEBCRM_INTEGRATION=true'
    - 'CODECLIMATE_REPO_TOKEN=81caf6b3c3c3587d37103c70e5213cab4c2fee6b08918557736baa075021b6d0'
    - secure: "dRGHULKMHj8/9Y7L1JMc+RwjD6c+djCBvQsewVGII+a5loiRQFV72zb5Td0JBPzGI2K1t3EXc2F8X8D+1QR+jpb0SFFSAUHzb2mvWU+FPixHfTxAPpktfiT+qAHFPkeaQMY86ktosE50+J555ke8YbtRKIBsqDbvZU+vnr3N6Ui4JhomCPMyCmnuFFATHoGBdhcrvWc1vY1Z7gK/qd0nhgyDb+sfOnbLinz7qR4oEI2nbGA6z5AzwfbD4JkXqagPirQy2tUJGAY71QVpDevg3qjfV2Hb9Ow1ESW9M0DsZZjFXXx6VJ4z9xikaqdauUMcJSCNMXtSK6OIUiy7Ln+WQKjDuGLxOLpG5oUxV7FrKEp63cQX9+6BDEPRuilwumZMBP0goE0kMFZmjai1bm3sMCddm08i05w9NraswxRHElBlPQxAXCDtiEQR2PKkI0G9j1/OheTvxn73GK0owPA6aOpOn52Jp+nwt8llZzPCLMvax4CmECESRvIJ7MN+ye1yre4IopXnbdZhHo/eoeGO0WTZL/t3qrmjGPyTljTkwGgp3LI+NxIoZG6UjOo2WJb6A3D8eZRbmMphZns1j7zcSUrCRNmpS6UmPsG1jExz+65LMSbScMs5xvCEtyW1X7qznf1NKLsfJxQUF3LlLSUrp/LoSTaDsrcR0E9qU9xt7/c="

  matrix:
    - 'TRAVIS_RAILS_VERSION=6.0'
    - 'TRAVIS_RAILS_VERSION=5.2'
    - 'TRAVIS_RAILS_VERSION=5.1'
    - 'TRAVIS_RAILS_VERSION=5.0'

matrix:
  exclude:
    - rvm: 2.3.8
      env: 'TRAVIS_RAILS_VERSION=6.0'
    - rvm: 2.4.7
      env: 'TRAVIS_RAILS_VERSION=6.0'
